name: Lint Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches: main
permissions: read-all
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - name: Install dependencies
        run: sudo apt-get install libsdl2-dev libxkbcommon-dev
      - name: Get Raylib
        run: go get -v -u github.com/gen2brain/raylib-go/raylib
      - name: Get Carcassonne-Engine
        run: go get -u github.com/YetAnotherSpieskowcy/Carcassonne-Engine@main
      - name: Lint Code Base
        uses: super-linter/super-linter@v6.3.1
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: origin/main
          VALIDATE_GO: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
